import Link from "next/link";
import { getUpdates } from "../lib/queries";
export const revalidate = 3600;
const QUICK_LINKS = [
 {href:"/jobs",label:"Latest Government Jobs",tone:"red",icon:"💼"},{href:"/results",label:"Latest Results",tone:"green",icon:"🏆"},{href:"/admit-card",label:"Admit Cards",tone:"orange",icon:"🎫"},{href:"/take-test",label:"Take Free Test",tone:"gold",icon:"📝"},{href:"/answer-key",label:"Answer Keys",tone:"blue",icon:"🔑"},{href:"/notification",label:"Notifications",tone:"purple",icon:"🔔"},{href:"/syllabus",label:"Syllabus",tone:"teal",icon:"📚"},{href:"/government-schemes",label:"Govt Schemes",tone:"pink",icon:"🇮🇳"},
];
const SECTIONS=[{key:"JOB",title:"Latest Government Jobs",href:"/jobs"},{key:"ADMIT_CARD",title:"Latest Admit Cards",href:"/admit-card"},{key:"RESULT",title:"Latest Results",href:"/results"}];
function safeText(value,fallback=""){if(value===null||value===undefined)return fallback;if(typeof value==="string"||typeof value==="number")return String(value);if(typeof value==="boolean")return value?"Yes":"No";if(Array.isArray(value))return value.map(item=>safeText(item)).filter(Boolean).join(", ")||fallback;if(typeof value==="object")return Object.values(value).map(item=>safeText(item)).filter(Boolean).join(", ")||fallback;return fallback;}
function formatDate(dateStr){if(!dateStr||typeof dateStr==="object")return "";const date=new Date(dateStr);if(Number.isNaN(date.getTime()))return "";return date.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});}
function UpdateList({title,href,items}){return <section className="portal-column"><div className="column-title"><span>{title}</span><Link href={href}>View All →</Link></div><div className="column-body">{items.length===0?<p className="empty-column">No updates available yet.</p>:items.map(item=>{const titleText=safeText(item?.title,"Untitled Update");const slug=safeText(item?.slug,"");return <article key={item.id} className="portal-item"><div className="item-status">NEW</div>{slug?<Link href={`/job/${slug}`} className="item-link">{titleText}</Link>:<span className="item-link">{titleText}</span>}{item?.published_date&&<time>{formatDate(item.published_date)}</time>}</article>})}</div></section>}
export default async function HomePage(){const [updates,jobs,admitCards,results]=await Promise.all([getUpdates({limit:60}),getUpdates({category:"JOB",limit:8}),getUpdates({category:"ADMIT_CARD",limit:8}),getUpdates({category:"RESULT",limit:8})]);const byCategory=category=>{if(category==="JOB"&&jobs.length)return jobs;if(category==="ADMIT_CARD"&&admitCards.length)return admitCards;if(category==="RESULT"&&results.length)return results;const exact=updates.filter(item=>safeText(item?.category).toUpperCase()===category);if(exact.length)return exact.slice(0,8);if(category==="ADMIT_CARD")return updates.filter(item=>{const text=`${safeText(item?.title)} ${safeText(item?.description)}`.toLowerCase();return /admit|hall ticket|call letter|exam city|download card|exam date/.test(text);}).slice(0,8);return [];};return <div className="portal-page">
 <section className="welcome-panel"><span className="home-eyebrow">🇮🇳 INDIA'S GOVERNMENT JOB & EXAM PLATFORM</span><h1>Government Jobs, Results, Admit Cards & Mock Tests</h1><p>Find verified government opportunities, official notifications and exam preparation resources — all in one place.</p><div className="home-actions"><Link href="/jobs" className="home-primary">🔎 Find Latest Jobs</Link><Link href="/take-test" className="home-secondary">📝 Start Free Mock Test</Link></div></section>
 <section className="quick-grid" aria-label="Quick links">{QUICK_LINKS.map(item=><Link key={item.href} href={item.href} className={`quick-card ${item.tone}`}><span>{item.icon}</span>{item.label}</Link>)}</section>
 <section className="test-promo"><div><span className="home-eyebrow">NEW • DAILY PRACTICE</span><h2>Prepare for Government Exams with Free MCQ Tests</h2><p>Practice GK, Reasoning, Quantitative Aptitude, English, Computer, Polity, History, Uttarakhand GK and SSC-style questions with instant results.</p></div><Link href="/take-test" className="promo-button">Take Test →</Link></section>
 <section className="notice-bar"><strong>🔴 Latest Updates</strong><span>New jobs, results and admit cards are added automatically. Always check the official notification before applying.</span></section>
 <div className="portal-section-heading"><div><span className="home-eyebrow">LATEST UPDATES</span><h2>What’s New Today</h2></div><Link href="/search">Search all updates →</Link></div>
 <section className="three-columns">{SECTIONS.map(section=><UpdateList key={section.key} title={section.title} href={section.href} items={byCategory(section.key)}/>)}</section>
 <section className="portal-section-heading lower"><div><span className="home-eyebrow">EXPLORE</span><h2>Everything You Need for Exam Preparation</h2></div></section>
 <section className="category-grid"><CategoryBox icon="💼" title="Government Jobs" href="/jobs" text="Browse latest vacancies with eligibility, important dates and official application links."/><CategoryBox icon="🎫" title="Admit Cards" href="/admit-card" text="Find hall tickets, exam dates and official download links."/><CategoryBox icon="🏆" title="Results" href="/results" text="Check recruitment and examination results from official sources."/><CategoryBox icon="📝" title="Free Mock Tests" href="/take-test" text="Take timed subject-wise MCQ tests and instantly review your performance."/></section>
 </div>}
function CategoryBox({icon,title,href,text}){return <section className="category-box"><span className="category-icon">{icon}</span><h2><Link href={href}>{title}</Link></h2><p>{text}</p><Link href={href} className="category-more">Explore →</Link></section>}
