create table if not exists public.auth_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('login','signup','logout')),
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists auth_activity_user_id_created_at_idx
  on public.auth_activity(user_id, created_at desc);

alter table public.auth_activity enable row level security;

revoke all on public.auth_activity from anon, authenticated;
grant select, insert on public.auth_activity to service_role;

-- No client-side user can read this table. The server route verifies the
-- authenticated JWT before inserting; the admin route reads it with the
-- server-only Supabase secret after checking ADMIN_EMAILS.
